apiVersion: apps/v1
kind: Deployment
metadata:
  name: msps
  namespace: kukala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msps
  template:
    metadata:
      labels:
        app: msps
    spec:
      containers:
      - name: msps
        image: docker.sohato.com/kukala/msps/production:v854
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: msps
  namespace: kukala
spec:
  selector:
    app: msps
  ports:
  - port: 80
    targetPort: 3000
