apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsps
  namespace: kukala
spec:
  replica: 3
  selector:
    matchLabels:
      app: wsps
  template:
    metadata:
      labels:
        app: wsps
    spec:
      containers:
      - name: wsps
        image: docker.sohato.com/kukala/wsps/production:v141
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wsps
  namespace: kukala
spec:
  selector:
    app: wsps
  ports:
  - port: 80
    targetPort: 3000
