apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukala-cmas-api
  namespace: stage-kukala
spec:
  selector:
    matchLabels:
      app: kukala-cmas-api
  template:
    metadata:
      labels:
        app: kukala-cmas-api
    spec:
      containers:
      - name: kukala-cmas-api
        image: docker.sohato.com/kukala/cmas/stage:v6
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Stage
          - name: ExternalService__CaptionAnalyseUrl
            value: http://kukala-sems-api/analyse?input=
          - name: ExternalService__SEMSUrl
            value: http://kukala-sems-api/api/BasicInfo/GetParetCategory?parentCategoryId=

        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kukala-cmas-api
  namespace: stage-kukala
spec:
  selector:
    app: kukala-cmas-api
  ports:
  - port: 80
    targetPort: 80
