apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukala-coms-api
  namespace: stage-kukala
spec:
  selector:
    matchLabels:
      app: kukala-coms-api
  template:
    metadata:
      labels:
        app: kukala-coms-api
    spec:
      containers:
      - name: kukala-coms-api
        image: docker.sohato.com/kukala/coms/stage:v23
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Stage
          - name: ApplicationSettings__SEMSService__PostGetbyListIdUrl
            value: http://kukala-sems-api/api/Post/GetByListId?
          - name: ApplicationSettings__SEMSService__GetPostInfoByUserNameUrl
            value: http://kukala-sems-api/api/Post/GetPostInfoByUserName?userName=
          - name: ApplicationSettings__SEMSService__GetPostsInfoByIds
            value: http://kukala-sems-api/api/Post/Search?
          - name: ApplicationSettings__SEMSService__SearchUrl
            value: http://kukala-sems-api/api/Post/Search

        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kukala-coms-api
  namespace: stage-kukala
spec:
  selector:
    app: kukala-coms-api
  ports:
  - port: 80
    targetPort: 80
