apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stage-kukala
  namespace: stage-kukala
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
      - stage-api.kukala.ir
      secretName: star-kukala-ir
  rules:
  - host: stage-api.kukala.ir
    http:
      paths:
      - backend:
          service:
            name: kukala-sems-api
            port:
              number: 80
        path: /sems
        pathType: Prefix

  - host: stage-api.kukala.ir
    http:
      paths:
      - backend:
          service:
            name: kukala-voms-api
            port:
              number: 80
        path: /voms
        pathType: Prefix
  
  - host: stage-api.kukala.ir
    http:
      paths:
      - backend:
          service:
            name: kukala-cmas-api
            port:
              number: 80
        path: /cmas
        pathType: Prefix

  - host: stage-api.kukala.ir
    http:
        paths:
        - backend:
            service:
              name: kukala-coms-api
              port:
                number: 80
          path: /coms
          pathType: Prefix

  - host: stage-api.kukala.ir
    http:
        paths:
        - backend:
            service:
              name: kukala-edps-api
              port:
                number: 80
          path: /edps
          pathType: Prefix

  - host: stage-api.kukala.ir
    http:
        paths:
        - backend:
            service:
              name: kukala-edps-worker
              port:
                number: 80
          path: /edps-worker
          pathType: Prefix

