apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukala-sems-api
  namespace: stage-kukala
spec:
  selector:
    matchLabels:
      app: kukala-sems-api
  template:
    metadata:
      labels:
        app: kukala-sems-api
    spec:
      containers:
      - name: kukala-sems-api
        image: docker.sohato.com/kukala/sems/stage:v166
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: ExternalService__ComsService__GetCommentByPostIdUrl
            value: http://kukala-coms-api/api/Comment/GetByPagination?Page=1&Count=10&postId=
          - name: ExternalService__VomsService__GetDetailStoreUrl
            value: http://kukala-voms-api/api/Vendor/StoreDetail?instaUserName=
          - name: ASPNETCORE_ENVIRONMENT
            value: Stage

        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kukala-sems-api
  namespace: stage-kukala
spec:
  selector:
    app: kukala-sems-api
  ports:
  - port: 80
    targetPort: 80
