apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukala-voms-api
  namespace: stage-kukala
spec:
  selector:
    matchLabels:
      app: kukala-voms-api
  template:
    metadata:
      labels:
        app: kukala-voms-api
    spec:
      containers:
      - name: kukala-voms-api
        image: docker.sohato.com/kukala/voms/stage:v17
        env:
          - name: ApplicationSettings__ExternalService__IDPService__AddRoleUrl
            value: http://kukala-idp-api/api/user/AddRole
          - name: ApplicationSettings__ExternalService__SEMSService__PostGetbyListIdUrl
            value: http://kukala-sems-api/api/Post/GetByListId?
          - name: ApplicationSettings__ExternalService__SEMSService__GetPostInfoByUserNameUrl
            value: http://kukala-sems-api/api/Post/GetPostInfoByUserName?userName=
          - name: ApplicationSettings__ExternalService__SEMSService__SearchUrl
            value: http://kukala-sems-api/api/Post/Search
          - name: ApplicationSettings__ExternalService__SEMSService__UpdatePostInfoUrl
            value: "http://kukala-sems-api/api/Post/UpdatePostInfo"
          - name: ApplicationSettings__ExternalService__SEMSService__GetDetailUrl            
            value: "http://kukala-sems-api/api/Post/GetDetail?postId="
          - name: ApplicationSettings__ExternalService__SEMSService__UpdateStockUrl
            value: "http://kukala-sems-api/api/Post/UpdateStock"
          - name: ApplicationSettings__ExternalService__SEMSService__GetDashboardUrl
            value: "http://kukala-sems-api/api/Post/GetDashboard"
          - name: ApplicationSettings__ExternalService__IDCSService__AddOrUpdateAccountUrl
            value: http://kukala-idcs-api/api/Account/AddOrUpdate

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kukala-voms-api
  namespace: stage-kukala
spec:
  selector:
    app: kukala-voms-api
  ports:
  - port: 80
    targetPort: 80
