global:
  imageRegistry: "docker.sohato.com"
  storageClass: "zfs-hdd"

ingress:
  enabled: true
  hostname: s3.sohato.com
  ingressClassName: nginx
  tls: true

apiIngress:
  enabled: true
  hostname: s3-api.sohato.com
  ingressClassName: nginx
  tls: true
persistence:
  size: 25Gi

metrics:
  serviceMonitor:
    enabled: true

  
