global:
  imageRegistry: "docker.sohato.com"
  storageClass: "zfs-hdd"

ingress:
  enabled: true
  hostname: s3.sohato.com
  ingressClassName: nginx
  tls: true
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"   



apiIngress:
  enabled: true
  hostname: s3.sohato.com
  ingressClassName: nginx
  tls: true
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"   

persistence:
  size: 25Gi

metrics:
  serviceMonitor:
    enabled: true

  
